### PR TITLE
Support for WS2812 RGB LED Strip

### PR DESCRIPTION
**Pull request by wizmo2**
Ongoing code changes to support the TTGO TAudio features. This follows up on the previous draft release (#93). 

Was originally based on the work @rochuck has done in the SqueezeAmpToo code (#46), but with significant changes.  It's evolved into something a little more complex that I would have liked and could probably do with optimizing in places.  

**_Current features_**
- Generic support for WS8212 based RGB strips upto 256 Leds.
- Built in Audio visualizer effects.
- Remote LED control through LMS CLI commands (for example Home-Assistant Notifications). 
- Full integration into LMS Plugin and new UI

[youtube link](https://youtu.be/1PFEcQugR4s)
[project link](https://github.com/wizmo2/TAudio-Case)

**_How To_**
1. For non-TAudio hardware, connect the D-IN to an unused gpio pin, and the GND to the ESP32 Gnd.  For larger strips you may (/will) need an external power supply for the VCC, otherwise you maybe able to use the 5V pin.
2. Flash (or re-flash) the device to update the ota partition, and upgrade squeezelite.bin (if not done in during flashing).
4. Set the LED Strip configuration (or NVS led_vu_config) to `WS2812,length=<n>,gpio=<gpio>, where <n> is the number of leds in the strip (1..255), and <gpio> is the data pin.`  For example, the TAUDIO configuration is **WS2812,length=19,gpio=22**.  
NOTE:  The TAudio shares the gpio output with the GREEN Led (if you have previously configured the SET_GPIO, remove the 'green' configuration). **Reboot is required after configuration changes**

**_ToDo_**
1. Bump plugin version.
2. Support other LED devices (only WS2812, but the led_strip library does support others)
3. Currently pauses displayer task for a second on "ledd" message.  May want to look at adding a pause_time to the packet and only pausing the led_display update.
4. Add "led_visual" (for effect toggle) to list of assignable button controls ("now_playing" may also be useful for display visual toggle). 
5. Look at adding a reserved status led (as per @rochuck and battery status).  Would need to be configurable and prevent updates/clear during built-in effects.
6. Potentially look into a full ArtNet/DMX plugin for LMS to interface with the dmx message. Would need a udp listener and have some type of scene/patch translation configuration.
7. Modify Readme, ?Create a custom locked TTGO TAudio hardware platform.

### CODE REVIEW

**Comment by philippe44** [comment]
Do you consider this PR ready for merge review now?

**Comment by wizmo2** [comment]
Yes.  Just updated the README.  Have been testing on a couple of different TAUDIO devices and a ESP32-CAM with an external strip.  Have not seen any stability issues.  As promised, will support any issues that may arise.

**Comment by wizmo2** [comment]
The one thing that is now broken(in master-cmaker), is visualizations when streaming from BT (mind was surprised this ever worked!).  I tracked it partially down to the changes in [AAC-SBR optimizations](https://github.com/sle118/squeezelite-esp32/commit/1fc7675c14a6f3380007d829ff322bfd01eb04cf) to output_i2s.c.  The buffer never gets full enough, so visu_export doesn't gets called.  I had a go at reducing the threshold, but it got a little deep for me.  It's possible the displayer changes we made for the previous PR are also involved.

**Comment by philippe44** [comment]
I'll have a look at that. These optimisations were a bit delicate but one thing was to leave as much CPU as possible for audio processing until we have enough buffered but we may never reach that level in BT or we might not need it

**Comment by philippe44** [comment]
I've added a change that re-enables visu_export regardless of buffer fullness in BT/AirPlay mode but I don't understand why it worked before because the calls to the led_update are not made when the display is controlled by the BT/AirPlay displayer. It is only done when controlled by the squeezelite displayer (unless you changed that as well)

**Comment by wizmo2** [comment]
Cool.  Will check it out.  Have not made any changes to the display operation.  I think the old code left the visu.mode running.

**Comment by wizmo2** [comment]
That did fix it, but not convinced if you want to keep the display portion as is.  

The current rgbled.pm component of the  plugin code in this PR uses the play state to disable the led_visu.  The equivalent in the  core SqueezeBox2 display module (showVisualizer) overrides this if "NowPlaying" is being displayed.   I can do the same with the rgbled code (and it works great for the led).  I'll hold off for the moment based on how you feel about comments below.

The display visualizers does continue to update (as visu_draw is not blocked by displayer.owned).  The update is a little jerky as the main display component tasker controls the update, and when not scrolling it blocks.  I'm a little concerned there may be a possible conflict here.  May not be worth the risk just for the BT sink.

**Comment by philippe44** [comment]
I've not forgotten about this, I'm using my spare time currently for some Perl things in LMS

**Comment by wizmo2** [comment]
No problem, Thanks for the update.

**Comment by cucko** [comment]
any news on this? it would be really good to add led strips to my a1s board.

**Comment by pintomax** [comment]
I successfully tested LCD display but it would be very cool to have the VU meter LED strip.

@wizmo2 are you still working on it?

**Comment by wizmo2** [comment]
I still run this older build on most of my players.  I have RGB strips on a few of them (t-audio, dial projects) 

I'll have a look to see if I can still easily merge with the latest branch,  @philippe44 needs to make the call re full integration

**Comment by wizmo2** [comment]
Just re-merged this again.  Have not updated the release on my Fork as yet,

I did updated the plugin files and zip, but its necessary to manually update the server files, now that the repo is part of the default plugin set.

**Comment by sle118** [comment]
@wizmo2 could you try sending a pull request agaist master-v4.3 instead of master-cmake? We are trying not to introduce any new feature in master-cmake, as it is our stable branch while we are consolidating v4.3.

at some point, when we're confident that it is good for everyone to use as their regular version, v4.3 will become the default branch. As a matter of fact, we already started building releases out of it.

thank you!

**Comment by wizmo2** [comment]
Just having a quick look now.   Which release version of the IDF are you using for v4.3?

Edit:  Found in the dockerfile.  release 4.3.2 as of 2022/02/28

**Comment by wizmo2** [comment]
I submitted a new PR for the v4.3 branch. #202 

Do you want me to close this PR (or you can).
I was also considering creating a PR to update the README for the custom build instructions for the v4.3 branch including adding a`--branch` switch for the clone command / clarify the correct dockers/idf version.  

P.S.  Am I doing something wrong on the build number (failed checks)?

**Pull request closed without merging**
