### PR TITLE
Add Support for ESP32-A1S Development Board

### PR DESCRIPTION
**Pull request by thomaspreece**
The ESP32-A1S features an AC101 DAC built in so this code pulls in code that sets up the DAC. Most of the code is pulled from https://github.com/phkehl/esp32-a1s-audio_hal.

I've not done much in C and very little with CMake so was unsure where to put ac101.c/ac101.h/audio_hal.h (doesn't really make sense to have them in squeezelite folder). This PR currently is fully functional I am unsure what CMake incantation I'd have to put in if I move the above files into a new folder so some help would be welcome!

### CODE REVIEW

**Comment by eogmau** [comment]
Hi guys, tried to build for this board but getting a lot of errors, probably due to lack of knowledge.
Can you provide please the steps I need to follow to be able to get the build going correctly?

Thanks a lot.

**Comment by thomaspreece** [comment]
Sorry for the slow reply. 
This PR has diverged from the Master branch so you'll need to clone https://github.com/thomaspreece/squeezelite-esp32/tree/esp-a1s.
Then follow the instructions under "Building Squeezelite-esp32" in that repo. When you are doing the menu config you'll need to make sure you select ESP-A1S option otherwise it won't build for that

**Comment by philippe44** [comment]
If you look at my latest commit, there is a first cut of separating output_i2s from the backend. I've added A1S (see menuconfig options) but all I know at that point is that it compiles and links. It's very unlikely to work. My A1S hardware is not ready at this point. 

I've changed a lot the ac101 code, quite often for no reason except syntax which forces me to understand the code when I have to. I'm not saying this is good practice or my style is better, it's just a way to wrap my head around a small piece of code that I need to understand and I know I'll have to change anyway.

**Comment by philippe44** [comment]
So the A1S (module standaline) works with the latest commit

**Comment by eogmau** [comment]
Hi @philippe44 , thanks for making the changes and confirming that it works for ESP32-A1S.
Have tried to build form the latest master but fails for me, maybe I am doing something wrong.

I run the below commands in for build:
`docker build -t esp-idf .`
`docker run -i -t -v `pwd`:/workspace/squeezelite-esp32 esp-idf`
`make menuconfig`
`find . \( -name "*.cpp" -o -name "*.c" -o -name "*.h" \) -type f -print0 | xargs -0 grep -l "RECOVERY_APPLICATION" | xargs touch
	export PROJECT_NAME="recovery" 
	make -j4 all EXTRA_CPPFLAGS='-DRECOVERY_APPLICATION=1'`
`make flash`

After `make flash` I get below error. Any ideas what I am doing wrong?

image

**Comment by philippe44** [comment]
Which esp-did version are you using? We are currently @3.1.5

**Comment by eogmau** [comment]
@philippe44  thanks for reply. I am using docker on ubuntu with the Dockerfile from this repo.
I assume that the Dockerfile takes care of all dependencies including the required esp-idf version.

**Comment by philippe44** [comment]
That I don't know really. @sle118 did the docker instance but I've not used it

**Comment by eogmau** [comment]
Hi @philippe44, thanks for getting back to me.
Any plans to include ESP-A1S in the automated build process?

Have you got the compiled binaries for the ESP-A1S that you can share here with us?

Thanks for your help.

**Comment by sle118** [comment]
@eogmau, before you attempt to call make, you need to choose one of the targets in the "build-scripts" folder and copy its content inside of the root sdkconfig file.

**Comment by thomaspreece** [comment]
I have an old binary which I am currently using which I can upload later if it will help

**Comment by philippe44** [comment]
it's already in the automated build process. We have not released it yet

**Comment by sle118** [comment]
Closing as this is now supported

**Pull request closed without merging**
