### PR TITLE
Fix led_vu

### PR DESCRIPTION
**Pull request by wizmo2**
I reverted the change from the static struct in (https://github.com/sle118/squeezelite-esp32/commit/c7e4d9711c6c5bc8c13d185734b66d41744c543e)

Interrupts don't appear to be needed, so left it out

### CODE REVIEW

**Comment by philippe44** [comment]
But unfortunately you can't do that
```
static EXT_RAM_ATTR struct led_strip_t  led_strip_config = {
    .rgb_led_type      = RGB_LED_TYPE_WS2812,
    .gpio              = -1,
};
```
Because EXT_RAM_ATTR does not allow initialized memory

**Comment by wizmo2** [comment]
Ok.  moved back to function, but added static.

**Comment by philippe44** [comment]
Sorry to be a pain but when set to STATIC, it is then in IRAM which I'm trying to preserve. The only option is to write some code initializers...

**Comment by wizmo2** [comment]
Does this work? otherwise I'll need some pointers ( unmanaged C is not really my field!)

**Comment by philippe44** [comment]
Seems good

**Pull request merged**
