### PR TITLE
24bit SPDIF output

### PR DESCRIPTION
**Pull request by UrbanLienert**
This PR adds 24bit support for SPDIF and changes the 16bit version as well.
In spdif_convert() the parity bit is set instead of bit 24 of the audio samples.

### CODE REVIEW

**Comment by philippe44** [comment]
Thanks - Have you measured the CPU impact (make a comparison using high-accuracy esp time measures)? This is a pretty intense part of the app and for example, I had to tweaks things not so long ago with spdif and spotify (not even mentioning equalizer)

**Comment by UrbanLienert** [comment]
Yes, it seems the 24bit version is about 4% faster than the 20bit version and the new 16bit version gains around 17%.

**Comment by philippe44** [comment]
Thanks, that's great! One last thing: I discover recently why there was an issue with left/right inversion and fixed it, I trust you have verified there is no inversion here?

**Comment by UrbanLienert** [comment]
Yes, double checked right now. And found some unnecessary code, that I forgot to delete. Removed it.

**Comment by philippe44** [comment]
Can you hide vucp in the function as a static

**Comment by UrbanLienert** [comment]
I've put it in the spdif struct.

**Comment by philippe44** [comment]
Many thanks - I've made a few changes to add to the optimization game 😄 but people will be happy to have 24 bits

**Comment by philippe44** [comment]
There is potentially and issue with that PR, , see https://github.com/sle118/squeezelite-esp32/issues/333. @UrbanLienert, can you chime-in?

**Pull request merged**
