### PR TITLE
Add support for the TAS5713

### PR DESCRIPTION
**Pull request by rochuck**
This PR adds support for the TAS5713 (i.e older HiFiBerry AMP+)

A few things:
- This is a fabulous project, I just stumbled on this recently. Kudos.
- I needed a way to test out the code, and my old hifiberry was the only I2S device I had kicking around, hence this PR.
- I've tried to make this minimally invasive to your code base.
- Feel free to punt this. I won't be offended.
- I'm willing to contribute/test.

### CODE REVIEW

**Comment by philippe44** [comment]
Sorry, I totally missed that PR. I'll review it short, thank you

**Comment by rochuck** [comment]
No problem. I can update the README supported hardware section too, if you think it would be worthwhile.

**Comment by philippe44** [comment]
@rochuck : I've integrated your PR with a few modifications as I took that opportunity to refactor a bit the audio backend. I don't have a TAS5713, that would be great if you could tell me if it works. You now need to specific the "model" and i2c sda/scl in the dac_config parameter

**Comment by rochuck** [comment]
@philippe44 I tested the changes, and I have sound. Thank you! You can get more detail [here](https://github.com/rochuck/squeeze-amp-too) if you are interested.

**Comment by philippe44** [comment]
This is super cool! If you want me to add a SqueezeAmpToo build config, let me know!

**Pull request closed without merging**
